#!/usr/bin/env python

import sys
import json
from src.utils.cromwell import Cromwell

if __name__ == "__main__":

    crom = Cromwell()
    if sys.argv[1] == "submit":
        wdl = sys.argv[2]
        inp = sys.argv[3]
        inpd = json.load(open(inp))
        crom.submit(wdl, inpd)
    elif sys.argv[1] == "meta":
        job = sys.argv[2]
        meta = crom.meta(job)
        print(json.dumps(meta, indent=2))
    elif sys.argv[1] == "running":
        jobs = crom.query("Running")['results']
        for job in jobs:
            print(job)
    elif sys.argv[1] == "all":
        jobs = crom.query(None)['results']
        for job in jobs:
            if 'name' not in job:
                job['name'] = ''
            print('{id} {name} {status}'.format(**job))
#                    {'end': '2022-07-23T16:36:42.248Z', 'id': '33341eaa-cf0b-4515-ba45-c996fe759279', 'metadataArchiveStatus': 'Unarchived', 'name': 'gtdbtk2re', 'start': '2022-07-23T16:36:20.575Z', 'status': 'Succeeded', 'submission': '2022-07-23T16:36:01.174Z'}


